const LEVEL_ONE = {
  shapes: [TYPES.HALF_RECT,TYPES.THIRD_RECT,TYPES.FOURTH_SQUARE,TYPES.HALF_TRIANGLE],
  congruent: true
}
const LEVEL_TWO = {
  shapes: [TYPES.SIXTH_RECT,TYPES.EIGHTH_RECT,TYPES.FOURTH_RECT,TYPES.FOURTH_RIGHT_TRIANGLE],
  congruent: true
}
const LEVEL_THREE = {
  shapes: [TYPES.EIGHTH_TRIANGLE,TYPES.FOURTH_ISOCELES,TYPES.EIGHTH_RIGHT_TRIANGLE,TYPES.SIXTH_TRIANGLE],
  congruent: true
}
const LEVEL_FOUR = {
  shapes: [TYPES.HALF_TRIANGLE,TYPES.FOURTH_SQUARE,TYPES.HALF_RECT,TYPES.FOURTH_ISOCELES],
  congruent: false
}
const LEVEL_FIVE = {
  shapes: [TYPES.THIRD_RECT,TYPES.SIXTH_TRIANGLE,TYPES.FOURTH_RIGHT_TRIANGLE,TYPES.FOURTH_SQUARE,TYPES.EIGHTH_RECT],
  congruent: false
}
const LEVEL_SIX = {
  shapes: [TYPES.SIXTEENTH_TRIANGLE,TYPES.EIGHTH_ISOCELES,TYPES.THIRD_TRIANGLE,TYPES.PARALLELOGRAM,TYPES.EIGHTH_TRIANGLE,TYPES.EIGHTH_ISOCELES_TWO],
  congruent: false
}


const LEVELS = [LEVEL_ONE,LEVEL_TWO,LEVEL_THREE,LEVEL_FOUR,LEVEL_FIVE,LEVEL_SIX]
